### ISSUE TITLE
Init

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#1]
This is the first list of things that we need to do for the initial version of the work. Once we have something more concreat I will make more specific Issues if needed.

- project to be easy to swap and change data
- OG tags to be set correctly and working
- all images have alt text
- and bascially to have the page SEO friendly
- Plus the template needs to have a form with a thank you page. The form has to be hidden by default but can be add by a chagne in a file, and the form fields need to come from a YML file. This way I can make the form customiezd for each project. This means that there will need to be some Jquery to gett all the form fields and put them togheter - please reference how we submit the form from the Consulting page. 
- This is the page that I want to use, I payed for this template, and there is no changing the template, it is what it is. https://landkit.goodthemes.co/desktop-app.html

I want for the first step to take the template, brake it down to fit the Jekyll framework, and once that is all working. We are going to customize the template by removing or adding sections on the page.

**Comment by vosaul** [comment]
ok I'm starting

**Comment by vosaul** [comment]
How do I get Landkit source files?

**Comment by vosaul** [comment]
I started the conversion with repeated snippets (head, footer, navbar) and the home page.
Since there are about a hundred pages here, so as not to get confused, I continued in alphabetical order. Or maybe there are some priority pages that need to be converted first?

The beginning is slow, but then it will be faster, the structure is created, some fragments are reused, or have a similar structure.

**Comment by vosaul** [comment]
The best way seems to be to convert the pages according to the menu

**Comment by vosaul** [comment]
desktop-app page added

**Comment by davidgatti** [comment]
Closing, since now the discussion is in the PR, as a remidner, when you open a PR, you have to close the Issue, and the discussion is moved to the PR, do not keep commenting here.
