### ISSUE TITLE
Custom URL to review

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#100]
Allow the ability to add a custom URL for both selected sections.

![Screen Shot 2020-12-04 at 10 10 25 AM](https://user-images.githubusercontent.com/411114/101144861-3d921c00-3619-11eb-80ec-cb9269ed70e5.png)

**Comment by edhenderson** [comment]
Should the custom URL wrap around the *AWS Marketplace* or appear below, e.g.

```
AWS Marketplace
Noel T
http://yahoo.com
```

**Comment by davidgatti** [comment]
It should wrap around bot line of text.

**Comment by edhenderson** [comment]
So it needs to wrap around `Noel T`? That should be the link?

**Comment by davidgatti** [comment]
Treat

```
AWS Marketplace
Noel T
```

as one thing, wrap the <a> from the letter `A` till the letter `T`

**Comment by edhenderson** [comment]
@davidgatti OK understood, thank you.
