### ISSUE TITLE
Add a - read more feature

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#119]
Add a read more feature to chop of reviews that are to long. When clicked the full text should show up

![Screen Shot 2021-03-21 at 10 38 10 AM](https://user-images.githubusercontent.com/411114/111900756-9bb20600-8a34-11eb-8cf9-0ad46b6ec88c.png)

**Comment by x5hwuk7nc6jsudcc** [comment]
This feature is ready for testing in PR https://github.com/0x4447-office/0x4447_template_office_jekyll/pull/138

This uses Bootstrap's native utilities with no custom css/js.  

You can configure the number of characters to truncate by changing the `textlimit` variable in the `testimonials.html` include.
