### ISSUE TITLE
Visually remove the URL color

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#120]
The user name should be black, and not blue despite being still a URL

![Screen Shot 2021-03-21 at 10 38 14 AM](https://user-images.githubusercontent.com/411114/111900928-77a2f480-8a35-11eb-858f-067da0a831fb.png)

**Comment by x5hwuk7nc6jsudcc** [comment]
This is resolved in PR https://github.com/0x4447-office/0x4447_template_office_jekyll/pull/137

Using Bootstrap's `text-body` color utility class.
