### ISSUE TITLE
Align the extra features

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#121]
The extra features are not correctly aligned.

![Screen Shot 2021-03-21 at 10 38 18 AM](https://user-images.githubusercontent.com/411114/111900958-a28d4880-8a35-11eb-95af-dea352d73542.png)

**Comment by x5hwuk7nc6jsudcc** [comment]
This is resolved in PR https://github.com/0x4447-office/0x4447_template_office_jekyll/pull/136

I note this doesn't collapse very elegantly for viewports 768-1200px.  I would normally resolve this at the same time but I'm not sure how you would want this to collapse so I'll leave it to you to open a new issue,.
