### ISSUE TITLE
Remove distortion and animation

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#122]
In bot places remove the distortion and animations, we will use fixed images.

![Screen Shot 2021-03-21 at 10 38 23 AM](https://user-images.githubusercontent.com/411114/111900975-b89b0900-8a35-11eb-871a-12b9a2bea07f.png)
![Screen Shot 2021-03-21 at 10 38 25 AM](https://user-images.githubusercontent.com/411114/111900980-ba64cc80-8a35-11eb-9e8b-fd62ca77ff08.png)

**Comment by x5hwuk7nc6jsudcc** [comment]
Should be resolved in PR https://github.com/0x4447-office/0x4447_template_office_jekyll/pull/135.

Note I added the "fade up" effect to the first image so it matches the adjacent column.  I can remove this if you like.
