### ISSUE TITLE
Remove social icons

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#125]
![Screen Shot 2021-03-21 at 10 39 31 AM](https://user-images.githubusercontent.com/411114/111901055-09aafd00-8a36-11eb-8be8-4e7cd3b75a9e.png)

**Comment by x5hwuk7nc6jsudcc** [comment]
Resolved in PR https://github.com/0x4447-office/0x4447_template_office_jekyll/pull/133
