### ISSUE TITLE
Added header from template

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#126]
![Screen Shot 2021-03-21 at 10 39 55 AM](https://user-images.githubusercontent.com/411114/111901068-129bce80-8a36-11eb-9020-f793e85aa077.png)

**Comment by x5hwuk7nc6jsudcc** [comment]
Hey @davidgatti 

Can you give me a bit more info on this ticket? 

Do you want to add an existing header template into this page - or do you want to turn the header of this page into a template and call it in properly?

Thanks

**Comment by davidgatti** [comment]
Sorry, here is the explanation:

On this site: https://consulting.0x4447.com/schedule.html I have a bunch of pages with headers. and I want to include the same here. On this one the header got removed. And I want to re-add it. So I can put a nice custom image.

**Comment by x5hwuk7nc6jsudcc** [comment]
This is implemented in PR https://github.com/0x4447-office/0x4447_template_office_jekyll/pull/139

Note that I have added the base64 css backgrounds 'articles', 'contact' and 'schedule' to the `custom.scss` file. Normally I would add these as a separate stylesheet, but just following the convention of using a single sass file in this project.
