### ISSUE TITLE
The pricing section

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#13]
- attached image it think it is clear
- the height of the table needs to be fix and scroll inside
- Us the last style that you see here: https://landkit.goodthemes.co/docs/tables.html
- the data needs to come from a yml file. 

![Screen Shot 2020-09-17 at 9 02 47 AM](https://user-images.githubusercontent.com/411114/93432475-e5733580-f8c5-11ea-9de8-ed7e51145a68.png)

**Comment by vosaul** [comment]
done
