### ISSUE TITLE
Zig-Zag flow

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#149]
This is something few developers had an issue with to do it right. The ideal site has a zig-zag flow and I do think the template has this feature built in, the issue is that other developers had was the flipping of the image and text around for the middle section, they messed up all the margins and everything around. Either check if the template has this feature, or make it look good yourself using your best judgment.

if what I'm asking is not clear, please let me know so I can try to explain it in a different way.

![Screen Shot 2021-04-28 at 8 52 31 AM](https://user-images.githubusercontent.com/411114/116359518-2c7fbc80-a7ff-11eb-99de-01f844567f5c.png)

**Comment by x5hwuk7nc6jsudcc** [comment]
Hey @davidgatti 

Can you send me documentation to the theme or theme details so I can look it up?  Couldn't see any info in the repo.
I couldn't see any utilities or classes for this by searching the theme code, but doesn't mean it's not there.

If it's not already baked into the theme, it should still be relatively straightforward.  I just had a mess around with it in my css console and it can be done with css alone, although padding/margins will also need to be reversed or reset as you said.  Probably this is better done using liquid so the elements are displayed in the DOM in the correct order, and then we use css to correct the stacking order on mobile.  So yeah, few ways to do this, but let's check the theme docs first.

**Comment by davidgatti** [comment]
OK, this is the URL to the docs: https://landkit.goodthemes.co/docs/index.html see if there is something useful and then decide how to do it the best way it makes sense to you.

**Comment by x5hwuk7nc6jsudcc** [comment]
Hi @davidgatti 

Ok I can see it's just done manually with the Bootstrap classes.  The column order needs to be changed for desktop, but also the images need to be floated in the opposite direction as they overflow their container (see attached) which gives it that more interesting visual effect.  Probably need 45 mins to just go through each page and test.  You want me to add it as a milestone?
![example](https://user-images.githubusercontent.com/19599955/116632252-13f7d980-a99a-11eb-91c5-ad38ee8e9f96.png)

**Comment by davidgatti** [comment]
@x5hwuk7nc6jsudcc yes, sounds good to me.
