### ISSUE TITLE
Update the readme with the location of unique data

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#156]
I'd like to have a new section in the README.md files where we specify all the places in the project where the data needs to be changed to make the site unique. For example the main title, description and anything else that should be changed if the template is used for a different project.

**Comment by x5hwuk7nc6jsudcc** [comment]
This should now be resolvved in https://github.com/0x4447-office/0x4447_template_office_jekyll/pull/157
