### ISSUE TITLE
Remove unused transparent box

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#158]
![Screen Shot 2021-05-31 at 7 48 58 AM](https://user-images.githubusercontent.com/411114/120146448-63be0080-c1e5-11eb-8850-59ce9fb07389.png)

**Comment by x5hwuk7nc6jsudcc** [comment]
Resolved by https://github.com/0x4447-office/0x4447_template_office_jekyll/pull/161
