### ISSUE TITLE
Remove the computer

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#159]
- remove the mac
- remove the white background since the image is a transparent png

![Screen Shot 2021-05-31 at 7 49 04 AM](https://user-images.githubusercontent.com/411114/120146463-6caed200-c1e5-11eb-875f-32a2bf294a3f.png)

**Comment by x5hwuk7nc6jsudcc** [comment]
Resolved by https://github.com/0x4447-office/0x4447_template_office_jekyll/pull/160
