### ISSUE TITLE
Link feature to the section

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#24]
- when you click `Feature`
- when you click `Learn more`

![Screen Shot 2020-09-30 at 9 46 29 AM](https://user-images.githubusercontent.com/411114/94658308-eb740800-0302-11eb-8fdb-4702c68223e9.png)

**Comment by vosaul** [comment]
I made a link from the menu item "features" and from the button "Learn more" to this section. 
I hope I understood correctly?

**Comment by vosaul** [comment]
added in VS/#22-Add-new-menu-itme brunch
