### ISSUE TITLE
make a hidden page called get_discount

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#28]
No link anywhere, just a form

![Screen Shot 2020-10-01 at 9 34 50 AM](https://user-images.githubusercontent.com/411114/94782829-137b6e00-03cc-11eb-8113-fd6249a99af4.png)

**Comment by vosaul** [comment]
how should I make the input industry - like select or text input? If select - all kinds of industry or some limited list?
(I downloaded a list of US industry, it contains 218 items)

**Comment by vosaul** [comment]
![image](https://user-images.githubusercontent.com/28349676/94829434-31b88c80-0413-11eb-84c5-6b8d8b65f91a.png)
what is written here?

**Comment by davidgatti** [comment]
- Keep the industry as input so people are free to type what they want
- "Use Case"
- Looks almost good ;) if you check my sketch you would see the input fields at the top are organized in a different way.
