### ISSUE TITLE
Make the UI match the template

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#47]
This repo is based on this template: https://openvpn.awmarketplace.products.0x4447.com/ - I know they don't look the same ;) but they should. I'd like for the repo to match the look of the template.

Check the original Issue #1 to see what I was looking for, and see what this repo is missing.

**Comment by edhenderson** [comment]
Yes, I can see there is a mismatch in the header. Apart from that, it seems converted OK. I will fix that.

**Comment by edhenderson** [comment]
(actually, it looks like the error is in the template you bought), see attached

![Uploading screencapture-openvpn-awmarketplace-products-0x4447-index-html-2020-11-17-08_20_27.png…]()

**Comment by edhenderson** [comment]
![screencapture-openvpn-awmarketplace-products-0x4447-index-html-2020-11-17-08_20_27](https://user-images.githubusercontent.com/1378582/99364852-6773e080-28ae-11eb-92c6-f3fa23b28571.png)

**Comment by edhenderson** [comment]
This can be fixed (and has already been fixed in another pull request) #52
