### ISSUE TITLE
Key images to base64

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#48]
This two images need to be in base64

![Screen Shot 2020-11-16 at 8 41 54 AM](https://user-images.githubusercontent.com/411114/99225026-ab4fe280-27e7-11eb-9fbc-62ba3606cdac.png)

**Comment by edhenderson** [comment]
The Landkit logo has been replaced in another PR so I will replace the big dashboard thing.

https://github.com/0x4447-office/0x4447_template_office_jekyll/pull/53
