### ISSUE TITLE
Review the project

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#50]
And let me know if there is something to improve and if so how much each task will take.

**Comment by edhenderson** [comment]
I spent about 30m reviewing the project. While it's not always exactly how I would do it (and that's OK), its reasonably well structured. Suggestions on improvements:

- any SEO / PageSpeed improvements I mentioned already in other project
- removing files not used in website build (can always move them to an `_archive` folder or similar)
- cleanup config (removed unused config)
- better README
- check links
- test cross-browser / mobile
