### ISSUE TITLE
Check if margins are the same

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#57]
I think they are not, something is off without those logs.

![Screen Shot 2020-11-18 at 10 12 58 AM](https://user-images.githubusercontent.com/411114/99512568-e853da80-2989-11eb-8435-b10145c0139f.png)

**Comment by edhenderson** [comment]
The bottom gap is `mb-9` which is equating to `64px`
The top gap is the nav bar which is approximately `85px`

Will try to adjust the bottom gap.

**Comment by edhenderson** [comment]
I have upped the bottom gap to `mb-10` which is `80px` (this is the closest I can approximate).
