### ISSUE TITLE
Remove bar if no company

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#58]
This list is already coming from an array, but we need to extend this:

- if array empty remove the bar all-together from the UI.
- the array should contain objects with:
  - url to IMG with extension
  - string for the alt and title tag
  - images should have a fixed height so when new logos are added they will be in the same proportion even if the fiels will be all over the place, like raster mixed with vector.

![Screen Shot 2020-11-18 at 10 14 20 AM](https://user-images.githubusercontent.com/411114/99512702-11746b00-298a-11eb-882d-724ae54781a1.png)

**Comment by edhenderson** [comment]
The carousel thing is a third party library called Flickity - https://flickity.metafizzy.co/ - I had a look through its options to see if there was a way to constrain image height, I could not see one. It autosizes on render to your biggest image.

I'd suggest therefore when putting things in it, they are all of the same size-ish.

I've added a CSS rule to constrain for now and we can tweak later if needed.

**Comment by davidgatti** [comment]
@edhenderson as a reminder, when you open the PR, we move the discussion in the PR, otherwise I'm going to miss your comments. Issues are for acquiring additional info, PRs are for discussing the situation.

**Comment by edhenderson** [comment]
I think these comments were before I opened the PR as I heard your advice previously. But understand what your saying. Thanks.

**Comment by davidgatti** [comment]
Even if, the comment here, is about telling the progress of the work, which should be included in the PR which would give more context on the work that was done.
