### ISSUE TITLE
SEO tuning

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#68]
Based on this issue #50 I accounted for 2h of work, do as much as you can in 2h, and what is left, make a list down here, so we can make a new milestone.

**Comment by edhenderson** [comment]
From https://github.com/0x4447-office/0x4447_template_office_jekyll/issues/50 and X:

- [ ] any SEO / PageSpeed improvements I mentioned already in other project
- [ ] removing files not used in website build (can always move them to an _archive folder or similar)
- [ ] cleanup config (removed unused config)
- [ ] page <title>s
- [ ] better README
- [ ] check links
- [ ] test cross-browser / mobile

**Comment by edhenderson** [comment]
That is 2 hour Sir. See items above for a note of what I did.

**Comment by davidgatti** [comment]
OK, very cool, so the rest will take 2 more h?

**Comment by edhenderson** [comment]
Seems about right.
