### ISSUE TITLE
This strip needs to be dynamic

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#7]
![Screen Shot 2020-09-11 at 9 22 24 AM](https://user-images.githubusercontent.com/411114/92882646-62a73200-f410-11ea-9d17-308bfc2378a9.png)

This section of the page needs to come from an array, and the array needs to hold the names of the file to a logo for example:

for example:

```
[ "airbnb.png", "apple.jpg", etc]
```

**Comment by vosaul** [comment]
This is exactly what was done
![image](https://user-images.githubusercontent.com/28349676/92887578-4493fe80-f41d-11ea-8c2e-dbe8c88e06dd.png)

**Comment by vosaul** [comment]
of course, I can reject the path to the icons, leave only the names, but then you have to make sure that all the icons are in the same folder.
It's up to you

**Comment by vosaul** [comment]
There is another solution, it has its pros and cons. 
We can discard the brand.yml file and simply scan all the files in the brand's folder.
+ you will not need to edit the brand.yml file
- you will not be able to influence the order of placement of brands.

**Comment by davidgatti** [comment]
No this is perfect didn't know this was already done, all good.
