### ISSUE TITLE
Do the other half of the SEO work

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#82]
Description in the title :)

**Comment by edhenderson** [comment]
From #68 

- [ ] consider using <link rel=preload> to prioritize fetching resources that are currently requested later in page load
- [ ] reduce the number of requests
- [ ] cache policy on resources and assets (CSS, fonts, images, JS), there is none
- [ ] check all CSS requests to see if they required
- [ ] check all JS requests to see if they required
- [ ] test cross-browser / mobile
- [ ] removing files not used in website build (can always move them to an _archive folder or similar)

**Comment by edhenderson** [comment]
Tested in Firefox, Safari, Opera & Chrome
