### ISSUE TITLE
Add a 3rd section

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#95]
I need a third section that matches the alternating pattern. So the whole site needs to match.

![Screen Shot 2020-12-04 at 9 40 52 AM](https://user-images.githubusercontent.com/411114/101143687-86e16c00-3617-11eb-9cc5-db1cf8b6b1a2.png)

**Comment by edhenderson** [comment]
What should the content be for this section please?

**Comment by davidgatti** [comment]
Copy the placeholder image and text, I will replace it when I use it.

**Comment by edhenderson** [comment]
@davidgatti OK, understood. Can you clarify which section is the placeholder image and text? I want to make sure I duplicate the correct one. Thanks.

**Comment by davidgatti** [comment]
It needs to match the alternating patter, so there cna't be two withs one after the other, or two greys after each other. The color pattern on the whole page might chagne. I don't know, you have to check it out. and make sure it all looks good still.
