### ISSUE TITLE
Support button

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#97]
Add a button that links to here: https://support.0x4447.com/ Same button style as the one in the beginning of the page. Or any variant that will look good in there.

![Screen Shot 2020-12-04 at 9 43 20 AM](https://user-images.githubusercontent.com/411114/101143836-c27c3600-3617-11eb-9e23-29aca48c4834.png)

**Comment by edhenderson** [comment]
🏓
