### ISSUE TITLE
Reorganize the project folder and file structure

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#99]
Once you to all the other issues, I'd like to schedule a screen-share, where we I want to reorgaznie how the project is structured, and organized since right now it is illogically put together, and it is hard to find what is needed + there is way to much tenet that is not used. This way you can tell me from your perspective what makes sense and what doesn't

**Comment by edhenderson** [comment]
OK, when would you like to do this and how much time do you need please?

**Comment by davidgatti** [comment]
We can do it next week in the mornings? around 9AM your local time? for 30m to 1h?

**Comment by edhenderson** [comment]
I can do Wednesday morning 930-10? Would that work?

**Comment by davidgatti** [comment]
Pick a date and time that works for you: https://consulting.0x4447.com/schedule.html

**Comment by edhenderson** [comment]
Tuesday 1230-1300 is booked in your calendar.

**Comment by davidgatti** [comment]
As discussed over the phone.

**Comment by edhenderson** [comment]
Thats great. Agreed. This is part of next milestone?

**Comment by davidgatti** [comment]
@edhenderson Yes if you can write done all the notes that you did here, so we don't forget anything, and let me know how log do you think this will take.

**Comment by edhenderson** [comment]
- make a `content` directory for HTML
- remove ALL unnecessary images and have a `samples` directory

**Comment by edhenderson** [comment]
This is what I had @davidgatti

**Comment by davidgatti** [comment]
ok
